language: python
# For 3.7 support, see https://github.com/travis-ci/travis-ci/issues/9815
dist: xenial
sudo: yes
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt -r test_requirements.txt
  - pip install .
before_script:
  - flake8 --max-line-length 100 .
# command to run tests
script: pytest tests
